services:
  prediksi-ikan-teri:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        ADMIN_USERNAME: ${ADMIN_USERNAME}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        ADMIN_NAME: ${ADMIN_NAME}
        SECRET_KEY: ${SECRET_KEY}
    container_name: prediksi-ikan-teri
    restart: unless-stopped
    ports:
      - "5000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - NODE_ENV=production
    env_file:
      - .env